### ISSUE TITLE
peer to peer code review

### ISSUE THREAD

**Issue by Kayonga99** [ndayishimiyeeric/odalton-portfolio#5]
### Hey Oldaton we don't have much to say but to congratulate you, 🥳 🥳 your code is clean keep it up. 💯 
Happy coding! 😄 

- Its not always the most intelligent nor the most energetic who succed, but those who prepare to apply themselves  bit by bit, day in day out.

**Comment by ndayishimiyeeric** [comment]
### Thanks I will continue to work hard to be a Powerfull developer
